# Linear Algebra

In [2]:
import numpy as np
import scipy.linalg as la

### Basic operations:

In [3]:
def scalar_product(x, y):
    """
    Calculates scalar product of two vectors.
    Args:
        x (array_like): Vector of size n
        y (array_like): Vector of size n
    Returns:
        numpy.float32: scalar product of x and y
    """
    n = x.size
    z = 0.0
    for i in range(n):
        z += x[i] * y[i]
    return z

In [4]:
# test of the scalar_product function
x = np.random.rand(3)
y = np.random.rand(3)
print(scalar_product(x, y))
print(np.dot(x, y))

1.1625001781824815
1.1625001781824815


In [5]:
def matrix_vector_product(A, x):
    """
    Calculates matrix-vector product.
    Args:
        A (array_like): A m-by-n matrix
        x (array_like): Vector of size n
    Returns:
        numpy.ndarray: Matrix-vector product
    """
    m, n = A.shape
    b = np.zeros(m)
    for i in range(m):
        for j in range(n):
            b[i] += A[i,j] * x[j]
    return b

In [6]:
# test of the matrix_vector_product function
A = np.random.rand(3, 3)
x = np.random.rand(3)
print(matrix_vector_product(A, x))
print(np.dot(A, x))

[0.47731842 0.88645375 0.75157503]
[0.47731842 0.88645375 0.75157503]


In [7]:
def matrix_matrix_product(A, B):
    """
    Calculates matrix-matrix product.
    Args:
        A (array_like): A m-by-n matrix
        B (array_like): A n-by-p matrix
    Returns:
        numpy.ndarray: Matrix-matrix product
    """
    m, n = A.shape
    n, p = B.shape
    C = np.zeros((m, p))
    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i,j] += A[i,k] * B[k,j]
    return C

In [8]:
# test of the matrix_matrix_product function
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
print(matrix_matrix_product(A, B))
print(np.dot(A, B))

[[0.59026754 0.27782286 0.24958374]
 [0.74239856 1.03740225 0.23832123]
 [0.42386534 0.57792432 0.14190123]]
[[0.59026754 0.27782286 0.24958374]
 [0.74239856 1.03740225 0.23832123]
 [0.42386534 0.57792432 0.14190123]]


### Direct methods:

In [9]:
def forward_substitution(A, b):
    """
    Solves a system of linear equation with lower triangular matrix.
    Args:
        A (array_like): A n-by-n lower triangular matrix
        b (array_like): RHS vector of size n
    Returns:
        numpy.ndarray: Vector of solution
    """
    n, n = A.shape
    x = np.zeros(n)
    for i in range(0, n):
        x[i] = (b[i] - np.dot(A[i,:], x)) / A[i,i]
    return x

In [10]:
# test of the forward_substitution function
A = np.tril(np.random.rand(3, 3))
b = np.random.rand(3)
print(forward_substitution(A, b))
print(la.solve(A, b))

[ 1.08027608 -0.23544643  0.5321408 ]
[ 1.08027608 -0.23544643  0.5321408 ]


In [11]:
def backward_substitution(A, b):
    """
    Solves a system of linear equation with upper triangular matrix.
    Args:
        A (array_like): A n-by-n upper triangular matrix
        b (array_like): RHS vector of size n
    Returns:
        numpy.ndarray: Vector of solution
    """
    n, n = A.shape
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i,:], x)) / A[i,i]
    return x

In [12]:
# test of the backward_substitution function
A = np.triu(np.random.rand(3, 3))
b = np.random.rand(3)
print(backward_substitution(A, b))
print(la.solve(A, b))

[ 0.26187223 -0.68467364  0.76070378]
[ 0.26187223 -0.68467364  0.76070378]


In [13]:
def gaussian_elimination(A, b):
    """
    Transform given matrix into upper triangular form, perform identical operations on RHS vector.
    Args:
        A (array_like): A n-by-n regular matrix
        b (array_like): RHS vector of size n
    Returns:
        numpy.ndarray: Upper triangular matrix
        numpy.ndarray: RHS vector corresponding to upper triangular matrix
    """
    n, n = A.shape
    tmp = np.zeros((n, n+1))
    tmp[:,:-1] = A
    tmp[:,-1] = b
    for i in range(0, n):  
        # return the index of row having maximum value relatively to i (max_row 0 means that the i-th row has maximum)
        max_row = np.argmax(np.abs(A[i:,i]))
        if (max_row != 0):
            # swap i-th row with row having maximum value
            row_i = np.copy(tmp[i,:])
            tmp[i,:] = tmp[i+max_row,:]
            tmp[i+max_row,:] = row_i    
        for j in range(i+1, n):
            tmp[j,:] = tmp[j,:] - (tmp[j,i] / tmp[i,i]) * tmp[i,:]      
    return tmp[:,:-1], tmp[:,-1]

In [14]:
# test of the gaussian_elimination function
A = np.random.rand(3, 3)
b = np.random.rand(3)
A_upper, bb = gaussian_elimination(A, b)
print(backward_substitution(A_upper, bb))
print(la.solve(A, b))

[-0.78641861 -0.39066871  1.66106963]
[-0.78641861 -0.39066871  1.66106963]


In [15]:
def lu_decomposition(A):
    """
    Decompose given matrix into a product of a lower and an upper triangular matrix.
    Args:
        A (array_like): A n-by-n regular matrix
    Returns:
        numpy.ndarray: Lower triangular matrix
        numpy.ndarray: Upper triangular matrix
    """
    n, n = A.shape
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    for i in range(0, n):
        for j in range(i, n):
            U[i,j] = A[i,j] - np.dot(L[i,:], U[:,j])
            L[j,i] = (A[j,i] - np.dot(L[j,:], U[:,i])) / U[i,i]
    return L, U

In [16]:
# test of the lu_decomposition function
A = np.random.rand(3, 3)
b = np.random.rand(3)
L, U = lu_decomposition(A)
y = forward_substitution(L, b)
x = backward_substitution(U, y)
print(x)
print(la.solve(A, b))

[0.37792355 0.13615147 1.6204618 ]
[0.37792355 0.13615147 1.6204618 ]


In [17]:
def thomas_algorithm(A, f):
    """
    Solves system of linear equations with tridiagonal matrix using Thomas' algorithm.
    Args:
        A (array_like): A n-by-n regular matrix
        f (array_like): RHS vector of size n
    Returns:
        numpy.ndarray: Vector of solution
    """
    n, n = A.shape # get the size of input matrix
    c = np.diag(A, -1) # get elements below diagonal 
    a = np.diag(A, 0) # get elements on diagonal
    b = np.diag(A, 1) # get elements above diagonal
    c = np.insert(c, 0, 0.0) # insert 0 as a first element of c
    b = np.insert(b, b.size, 0.0) # insert 0 as a last element of b
    x = np.zeros(n)
    rho = np.zeros(n)
    mu  = np.zeros(n)
    mu[0] = -b[0] / a[0]
    rho[0] = f[0] / a[0]
    for i in range(1, n):
        mu[i] = -b[i] / (c[i] * mu[i-1] + a[i])
        rho[i] = (f[i] - c[i] * rho[i-1]) / (c[i] * mu[i-1] + a[i])
    x[n-1] = rho[n-1]
    for i in range(n-2, -1, -1):
        x[i] = mu[i] * x[i+1] + rho[i]
    return x

In [18]:
# test of the thomas_algorithm function
A = np.random.rand(5, 5)
b = np.random.rand(5)
# create tridiagonal matrix from random matrix A
A = np.triu(np.tril(A, 1), -1)
print(thomas_algorithm(A, b))
print(la.solve(A,b))

[ 6.98659571 -9.77164351 -6.81067224 11.82781622  5.89405517]
[ 6.98659571 -9.77164351 -6.81067224 11.82781622  5.89405517]


### Iterative methods:

In [19]:
def jacobi_method(A, b, max_it=500, eps=0.0):
    """
    Solves system of linear equations iteratively using Jacobi's algorithm.
    Args:
        A (array_like): A n-by-n regular matrix
        b (array_like): RHS vector of size n
        max_it (int): Maximum number of iterations
        eps (float): Error tolerance
    Returns:
        numpy.ndarray: Vector of solution
    """
    n, n = A.shape
    x = np.zeros(n)
    x_new = np.zeros(n)   
    for k in range(max_it):
        for i in range(n):
            x_new[i] = (1.0 / A[i,i]) * (b[i] - np.dot(A[i,:i], x[:i]) - np.dot(A[i,i+1:], x[i+1:]))           
        x = x_new
        if(la.norm(np.dot(A, x) - b) < eps):
            break   
    return x

In [20]:
# test of the jacobi_method function
A = np.random.rand(3, 3) + 10. * np.eye(3) # create diagonally dominant matrix to ensure convergence
b = np.random.rand(3)
print(jacobi_method(A, b, 20))
print(la.solve(A, b))

[0.07221979 0.07294135 0.08030085]
[0.07221979 0.07294135 0.08030085]


In [21]:
def gauss_seidel_method(A, b, max_it=500, eps=0.0):
    """
    Solves system of linear equations iteratively using Gauss-Seidel's algorithm.
    Args:
        A (array_like): A n-by-n regular matrix
        b (array_like): RHS vector of size n
        max_it (int): Maximum number of iterations
        eps (float): Error tolerance
    Returns:
        numpy.ndarray: Vector of solution
    """
    n, n = A.shape
    x = np.zeros(n)
    x_new = np.zeros(n)  
    for k in range(max_it):
        for i in range(n):
            x_new[i] = (1.0 / A[i,i]) * (b[i] - np.dot(A[i,:i], x_new[:i]) - np.dot(A[i,i+1:], x[i+1:]))      
        x = x_new
        if(la.norm(np.dot(A, x) - b) < eps):
            break  
    return x

In [22]:
# test of the gauss_seidel_method function
A = np.random.rand(3, 3) + 10. * np.eye(3) # create diagonally dominant matrix to ensure convergence
b = np.random.rand(3)
print(gauss_seidel_method(A, b, 20))
print(la.solve(A, b))

[0.06634536 0.02275534 0.05885862]
[0.06634536 0.02275534 0.05885862]


In [23]:
def successive_overrelaxation_method(A, b, omega=1.0, max_it=500, eps=0.0):
    """
    Solves system of linear equations iteratively using successive overrelaxation (SOR) method.
    Args:
        A (array_like): A n-by-n regular matrix
        b (array_like): RHS vector of size n
        max_it (int): Maximum number of iterations
        eps (float): Error tolerance
    Returns:
        numpy.ndarray: Vector of solution
    """
    n, n = A.shape
    x = np.zeros(n)
    x_new = np.zeros(n)
    for k in range(max_it):
        for i in range(n):
            x_new[i] = (1.0 / A[i,i]) * (b[i] - np.dot(A[i,:i], x_new[:i]) - np.dot(A[i,i+1:], x[i+1:]))
        x += omega * (x_new - x)
        if(la.norm(np.dot(A, x) - b) < eps):
            break
    return x

In [24]:
# test of the successive_overrelaxation_method function
A = np.random.rand(3, 3) + 10. * np.eye(3) # create diagonally dominant matrix to ensure convergence
b = np.random.rand(3)

L = np.tril(A, -1) # get lower triangular matrix with zeros on diagonal
U = np.triu(A, 1) # get upper triangular matrix with zeros on diagonal
D = A - L - U # get diagonal matrix
B = -np.dot(la.inv(D + L), U) # calculate iteration matrix
rho = np.max(np.abs(la.eigvals(B))) # find spectral radius (i.e. maximal eigenvalue in absolute value)
omega = 2.0 / (1.0 + np.sqrt(1.0 - rho**2)) # find optimal relaxation factor

print(successive_overrelaxation_method(A, b, omega, 20))
print(la.solve(A, b))

[0.00547568 0.01524196 0.06277615]
[0.00547568 0.01524196 0.06277615]


In [25]:
def power_iteration(A, max_it=500):
    """
    Finds the greatest eigen value (in absolute value) of given matrix and its corresponding eigenvector.
    Args:
        A (array_like): A n-by-n diagonalizable matrix
        max_it (int): Maximum number of iterations
    Returns:
        numpy.ndarray: Eigenvector corresponding to a greatest eigenvalue (in absolute value)
        float: Greatest eigenvalue (in absolute value)
    """
    n, n = A.shape
    eigen_vec = np.ones(n)
    for i in range(max_it):
        eigen_vec_new = np.dot(A, eigen_vec)
        eigen_vec = eigen_vec_new
    eigen_vec = eigen_vec / la.norm(eigen_vec_new)
    eigen_val = la.norm(np.dot(A, eigen_vec))
    return eigen_vec, eigen_val

In [26]:
# test of the power_iteration function
A = np.random.rand(3, 3)
e_vec, e_val = power_iteration(A, 20)
print(e_val)
print(np.max(np.abs(la.eigvals(A))))

1.071139527652675
1.0711395271078243


### Gradient methods:

In [27]:
def conjugate_gradient_method(A, b, x, eps=1.0e-10):
    """
    Solves system of linear equations using conjugate gradient method.
    Args:
        A (array_like): A n-by-n regular matrix
        b (array_like): RHS vector of size n
        x (array_like): Initial guess
        eps (float): Error tolerance
    Returns:
        numpy.ndarray: Vector of solution
    """
    r = b - np.dot(A, x)
    p = r
    rs_old = np.dot(r.T, r)
    for i in range(len(b)):
        Ap = np.dot(A, p)
        alpha = rs_old / (np.dot(p.T, Ap))
        x = x + np.dot(alpha, p)
        r = r - np.dot(alpha, Ap)
        rs_new = np.dot(r.T, r)
        if np.sqrt(rs_new) < eps:
            break
        p = r + np.dot((rs_new / rs_old), p);
        rs_old = rs_new;
    return x

In [28]:
# test of the conjugate_gradient_method function

n = 3 # size of the problem
A = np.random.rand(n, n)
A = np.tril(A) + np.tril(A, -1).T # generate random symmetric matrix (should check also wheter the matrix is positive-definite)
b = np.random.rand(n) # random RHS vector
x_0 = np.zeros(len(b)) # initial guess

print(conjugate_gradient_method(A, b, x_0))
print(la.solve(A, b))

[0.44143129 0.52422035 0.5080985 ]
[0.44143129 0.52422035 0.5080985 ]
